[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.6",
    "pandas>=2.2.2",
    "openpyxl>=3.1.5",
]

[tool.setuptools.packages.find]
include = ["core", "data", "config", "loader"]

